version: '3'

services:
  view:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_list_view
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - shared-network
    volumes:
      # Comentar temporariamente o mapeamento de volume para teste
      # - .:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  shared-network:
    external: true
